name: libmtp
description: A library for interacting with MTP-based device connections.
repository: https://github.com/jardon/libmtp.dart
version: 1.1.22-1
environment:
  sdk: ^3.11.0
dependencies:
  ffigen: ^20.1.1
