name: libmtp
description: A library for interacting with MTP-based device connections.
repository: https://github.com/jardon/libmtp.dart
environment:
  sdk: ^3.11.0
dependencies:
  ffi: ^2.2.0
dev_dependencies:
  ffigen: ^20.1.1
